### ISSUE TITLE
IndexError on line 470 in report.py

### ISSUE THREAD

**Issue by selplacei** [RiedleroD/Personal-YouTube-PDF-Report-Generator#1]
I am getting the following output:

	Generating Heat Map.....
	[[0 0 0 0 0 0 0 0 0 0 0 0]
	 [0 0 0 0 0 0 0 0 0 0 0 0]
	 [0 0 0 0 0 0 0 0 0 0 0 0]
	 [0 0 0 0 0 0 0 0 0 0 0 0]
	 [0 0 0 0 0 0 0 0 0 0 0 0]
	 [0 0 0 0 0 0 0 0 0 0 0 0]
	 [0 0 0 0 0 0 0 0 0 0 0 0]]
	Generating Word Cloud.....
	Calculating Your Activity Score.....
	Generating Bar Plot.....
	Combining Images into PDF.....
	Traceback (most recent call last):
	  File "/home/selplacei/Projects/youtubereport/report.py", line 533, in <module>
		visual.gen_pdf()
	  File "/home/selplacei/Projects/youtubereport/report.py", line 470, in gen_pdf
		print("First watched video: " + urls[-1])
	IndexError: list index out of range

The variable `urls` doesn't seem to be generated correctly in the HTML class in parse.py.

**Comment by RiedleroD** [comment]
There seems to be a problem regarding the program finding the links. Since my takeout data is german, can you please send me yours so I can fix the problem?
Please send a .zip or .7z file containing your Takeout data at github@riedler.wien (yes, that's my own domain). I will delete the files as soon as the error is fixed to protect your data.

**Comment by selplacei** [comment]
With all due respect and best intentions, I won't trust a random person with my data - as I have plenty of personal info in my takeout. Maybe you could find some other person to do it. Good luck.

**Comment by RiedleroD** [comment]
Thanks anyways. This issue can't be fixed otherwise, but I understand your concerns and respect your privacy.

**Comment by selplacei** [comment]
... That being said, wouldn't a fresh account's takeout work just for testing? I went ahead and created one, currently waiting on Google's download link.

**Comment by RiedleroD** [comment]
A fresh account likely doesn't have the necessary history, but it'd be great if you could send me the takeout data from your fresh account. I can't find the setting where I can change the preferred language of my google account, and fresh ones are german automatically...

**Comment by selplacei** [comment]
Sent it to the e-mail you specified earlier.

**Comment by RiedleroD** [comment]
Wow, this was a hassle. I hate locale issues now. Anyway, the issue should be resolved now. Thanks for everything you did, it helped me a lot.

**Comment by RiedleroD** [comment]
lol forgot to close the issue
